export:
  sheets:
    globals:
      spreadsheetId: defaultSheetId
      datetimeFormat: "%d/%m/%Y %H:%M:%S"
      dateFormat: "%d/%m/%Y"

    summary:
      - spreadsheetId: oneSpecificSheetId
        range: Summary
      - range: Basic Summary

    investments:
      - spreadsheetId: anotherSpecificSheetId
        range: Funds
        data: funds
      - range: Stocks
        data: stocks
      - range: Real State CF
        data: realStateCF
      - range: Mixed
        data:
          - factoring
          - realStateCF

    contributions:
      - range: Contributions
        data: periodic

    transactions:
      - range: Investment TXs
        data: investment
      - range: Account TXs
        data: account
        datetimeFormat: "%-Y-%-m-%-d / %-I:%-M:%-S %Z"
        dateFormat: "%-Y-%-m-%-d"
        filters:
          - field: entity
            values: TRADE_REPUBLIC
      - range: All TXs
        data: [ investment, account ]

    historic:
      - range: Factoring Historic
        # data is not available for historic
        filters:
          - field: productType
            values: FACTORING
          - field: state
            values:
              - COLLECTED
              - MANAGING_COLLECTION

scrape:
  enabledEntities:
    - UNICAJA

  virtual:
    enabled: true

    globals:
      spreadsheetId: defaultSheetId
      datetimeFormat: "%d/%m/%Y %H:%M:%S"
      dateFormat: "%d/%m/%Y"

    investments:
      - spreadsheetId: oneSpecificSheetId
        range: Deposits
        data: deposits
        datetimeFormat: "%d/%m/%Y %H:%M:%S"
        dateFormat: "%d/%m/%Y"

    transactions:
      - range: Investment TXs
        data: investment