overrides:
  brace-expansion: "2.0.1"
  tmp@<=0.2.3: ">=0.2.4"
  form-data@>=4.0.0 <4.0.4: ">=4.0.4"
  js-yaml@>=4.0.0 <4.1.1: ">=4.1.1"
  glob@>=10.2.0 <10.5.0: ">=10.5.0"
  mdast-util-to-hast@>=13.0.0 <13.2.1: ">=13.2.1"
