BASE_LABEL_DESCRIPTIONS = {
    "salary": "Salary, payroll, wages or pension received from an employer or public body",
    "business_income": "Income from self-employment, freelancing, invoices or own business sales",
    "rental_income": "Rent received from tenants for a property the user owns",
    "refunds": "Refunds, reimbursements, returns or chargebacks received",
    "gifts_received": "Money received as a gift from family or friends",
    "interest": "Interest or remuneration paid by the bank on account balances",
    "other_income": "Any other incoming money that does not fit another income category",
    "housing": "Rent paid, mortgage installments, community fees and home maintenance",
    "utilities": "Electricity, gas, water, internet, phone and other household utility bills",
    "groceries": "Supermarkets, grocery stores, food markets and household supplies",
    "restaurants": "Restaurants, bars, cafes, fast food and food delivery",
    "transport": "Fuel, public transport, taxis, ride sharing, parking, tolls and vehicle costs",
    "shopping": "Clothing, electronics, online marketplaces, department stores and general retail",
    "subscriptions": "Recurring digital services and memberships such as streaming, software or cloud storage",
    "health": "Pharmacies, doctors, dentists, hospitals, opticians and medical services",
    "insurance": "Insurance premiums for home, car, health, life or other policies",
    "education": "Tuition, schools, courses, books and learning materials",
    "leisure": "Entertainment, cinema, concerts, events, hobbies, games and sports activities",
    "travel": "Flights, hotels, holiday rentals, travel agencies and trips",
    "personal_care": "Hairdressers, beauty salons, cosmetics, spa and personal care",
    "pets": "Veterinarians, pet food and pet supplies",
    "family": "Childcare, kids expenses, allowances and support to family members",
    "gifts_donations": "Gifts bought for others, charity donations and contributions",
    "taxes": "Tax payments, public administration fees and fines",
    "bank_fees": "Bank commissions, maintenance fees, card fees and other banking charges",
    "cash_withdrawal": "ATM cash withdrawals",
    "debt_payments": "Loan installments, credit card settlements and other debt repayments",
    "other_expense": "Any other outgoing payment that does not fit another expense category",
    "internal_transfer": "Transfers between the user's own accounts or to themselves",
    "savings_investment": "Money moved to savings, brokers, investment platforms or pension plans",
}
