from enum import Enum


class Entity(str, Enum):
    MY_INVESTOR = "MY_INVESTOR",
    UNICAJA = "UNICAJA",
    TRADE_REPUBLIC = "TRADE_REPUBLIC"
    URBANITAE = "URBANITAE"
    WECITY = "WECITY"
    SEGO = "SEGO"


class Feature(Enum):
    POSITION = "POSITION",
    AUTO_CONTRIBUTIONS = "AUTO_CONTRIBUTIONS",
    TRANSACTIONS = "TRANSACTIONS"
