from enum import Enum


class Entity(str, Enum):
    MY_INVESTOR = "MY_INVESTOR",
    UNICAJA = "UNICAJA",
    TRADE_REPUBLIC = "TRADE_REPUBLIC"
    URBANITAE = "URBANITAE"
    WECITY = "WECITY"
    SEGO = "SEGO"


class Feature(str, Enum):
    POSITION = "POSITION",
    AUTO_CONTRIBUTIONS = "AUTO_CONTRIBUTIONS",
    TRANSACTIONS = "TRANSACTIONS"


ENTITY_FEATURES = {
    Entity.MY_INVESTOR: [Feature.POSITION, Feature.AUTO_CONTRIBUTIONS, Feature.TRANSACTIONS],
    Entity.UNICAJA: [Feature.POSITION],
    Entity.TRADE_REPUBLIC: [Feature.POSITION, Feature.TRANSACTIONS],
    Entity.URBANITAE: [Feature.POSITION, Feature.TRANSACTIONS],
    Entity.WECITY: [Feature.POSITION, Feature.TRANSACTIONS],
    Entity.SEGO: [Feature.POSITION, Feature.TRANSACTIONS],
}
